version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  target-branch: deps
  ignore:
  - dependency-name: gulp
    versions:
    - ">= 4.a, < 5"
  - dependency-name: tailwindcss
    versions:
    - ">= 1.a, < 2"
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: workbox-build
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-sw
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: gulp-purgecss
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: webpack-stream
    versions:
    - 6.1.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.2.1
